### ISSUE TITLE
Hardcoded link in Configuration.java throws error when installing locally

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Validator#1]
https://github.com/Informatievlaanderen/OSLO-Validator/blob/master/src/main/java/validator/OSLO2/Configuration.java

```java
public class Configuration {
	private String apConfig = "https://data.vlaanderen.be/shacl-validator-config.json";
	private static final String AP_CONFIG = "AP_CONFIG";
    private final LoadingCache<String, Map<String, APModel>> cache;
```

Fetching https://data.vlaanderen.be/shacl-validator-config.json throws a 404 error.

**Comment by wdullaer** [comment]
This is not a hardcoded link, it is the default value of a config variable.
You should set the AP_CONFIG value to where you want the configuration to be loaded from
```bash
AP_CONFIG=/path/to/config java -jar shacl-validator.jar
```
This is also mentioned in the README.

That said, I'll push a default value that actually resolved
